// server/proto/problem_gen.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: server/proto/problem_gen.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Generator_GenerateProblemSet_FullMethodName    = "/problemgen.Generator/GenerateProblemSet"
	Generator_GenerateProblemSetPDF_FullMethodName = "/problemgen.Generator/GenerateProblemSetPDF"
)

// GeneratorClient is the client API for Generator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Generator service definition
type GeneratorClient interface {
	// Generate a set of math problems based on user preferences
	GenerateProblemSet(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*ProblemSet, error)
	// Generate both problems and a PDF file containing them
	GenerateProblemSetPDF(ctx context.Context, in *ProblemSet, opts ...grpc.CallOption) (*PDFResponse, error)
}

type generatorClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneratorClient(cc grpc.ClientConnInterface) GeneratorClient {
	return &generatorClient{cc}
}

func (c *generatorClient) GenerateProblemSet(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*ProblemSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProblemSet)
	err := c.cc.Invoke(ctx, Generator_GenerateProblemSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorClient) GenerateProblemSetPDF(ctx context.Context, in *ProblemSet, opts ...grpc.CallOption) (*PDFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PDFResponse)
	err := c.cc.Invoke(ctx, Generator_GenerateProblemSetPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratorServer is the server API for Generator service.
// All implementations must embed UnimplementedGeneratorServer
// for forward compatibility.
//
// Generator service definition
type GeneratorServer interface {
	// Generate a set of math problems based on user preferences
	GenerateProblemSet(context.Context, *GenerateRequest) (*ProblemSet, error)
	// Generate both problems and a PDF file containing them
	GenerateProblemSetPDF(context.Context, *ProblemSet) (*PDFResponse, error)
	mustEmbedUnimplementedGeneratorServer()
}

// UnimplementedGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeneratorServer struct{}

func (UnimplementedGeneratorServer) GenerateProblemSet(context.Context, *GenerateRequest) (*ProblemSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateProblemSet not implemented")
}
func (UnimplementedGeneratorServer) GenerateProblemSetPDF(context.Context, *ProblemSet) (*PDFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateProblemSetPDF not implemented")
}
func (UnimplementedGeneratorServer) mustEmbedUnimplementedGeneratorServer() {}
func (UnimplementedGeneratorServer) testEmbeddedByValue()                   {}

// UnsafeGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneratorServer will
// result in compilation errors.
type UnsafeGeneratorServer interface {
	mustEmbedUnimplementedGeneratorServer()
}

func RegisterGeneratorServer(s grpc.ServiceRegistrar, srv GeneratorServer) {
	// If the following call pancis, it indicates UnimplementedGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Generator_ServiceDesc, srv)
}

func _Generator_GenerateProblemSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).GenerateProblemSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Generator_GenerateProblemSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).GenerateProblemSet(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Generator_GenerateProblemSetPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProblemSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).GenerateProblemSetPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Generator_GenerateProblemSetPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).GenerateProblemSetPDF(ctx, req.(*ProblemSet))
	}
	return interceptor(ctx, in, info, handler)
}

// Generator_ServiceDesc is the grpc.ServiceDesc for Generator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Generator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "problemgen.Generator",
	HandlerType: (*GeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateProblemSet",
			Handler:    _Generator_GenerateProblemSet_Handler,
		},
		{
			MethodName: "GenerateProblemSetPDF",
			Handler:    _Generator_GenerateProblemSetPDF_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/problem_gen.proto",
}
